/** @type {import('tailwindcss').Config} */

function em(px) {
   return `${px / 16.5}em`
}

export default {
   content: ['./index.html', './src/**/*.{js,ts,jsx,tsx,vue}'],
   theme: {
      extend: {
         colors: {
            white: 'rgb(var(--white) / <alpha-value>)',
            black: 'rgb(var(--black) / <alpha-value>)',
            body: 'rgb(var(--body) / <alpha-value>)',
            border: {
               DEFAULT: 'rgb(var(--border) / <alpha-value>)',
               active: 'rgb(var(--primary) / <alpha-value>)',
            },
            gray: {
               50: 'rgb(var(--gray-50) / <alpha-value>)',
               100: 'rgb(var(--gray-100) / <alpha-value>)',
               150: 'rgb(var(--gray-150) / <alpha-value>)',
               200: 'rgb(var(--gray-200) / <alpha-value>)',
               250: 'rgb(var(--gray-250) / <alpha-value>)',
               300: 'rgb(var(--gray-300) / <alpha-value>)',
               350: 'rgb(var(--gray-350) / <alpha-value>)',
               400: 'rgb(var(--gray-400) / <alpha-value>)',
               450: 'rgb(var(--gray-450) / <alpha-value>)',
               500: 'rgb(var(--gray-500) / <alpha-value>)',
               550: 'rgb(var(--gray-550) / <alpha-value>)',
               600: 'rgb(var(--gray-600) / <alpha-value>)',
               650: 'rgb(var(--gray-650) / <alpha-value>)',
               700: 'rgb(var(--gray-700) / <alpha-value>)',
               750: 'rgb(var(--gray-750) / <alpha-value>)',
               800: 'rgb(var(--gray-800) / <alpha-value>)',
               850: 'rgb(var(--gray-850) / <alpha-value>)',
               900: 'rgb(var(--gray-900) / <alpha-value>)',
               950: 'rgb(var(--gray-950) / <alpha-value>)',
            },
            primary: {
               light: 'rgb(var(--primary-light) / <alpha-value>)',
               DEFAULT: 'rgb(var(--primary) / <alpha-value>)',
               dark: 'rgb(var(--primary-dark) / <alpha-value>)',
               fg: 'rgb(var(--primary-fg) / <alpha-value>)',
               'fg-light': 'rgb(var(--primary-fg-light) / <alpha-value>)',
            },
            secondary: {
               DEFAULT: 'rgb(var(--secondary) / <alpha-value>)',
               dark: 'rgb(var(--secondary-dark) / <alpha-value>)',
               fg: 'rgb(var(--secondary-fg) / <alpha-value>)',
            },
            danger: {
               light: 'rgb(var(--danger-light) / <alpha-value>)',
               DEFAULT: 'rgb(var(--danger) / <alpha-value>)',
               dark: 'rgb(var(--danger-dark) / <alpha-value>)',
               fg: 'rgb(var(--danger-fg) / <alpha-value>)',
            },
            success: {
               light: 'rgb(var(--success-light) / <alpha-value>)',
               DEFAULT: 'rgb(var(--success) / <alpha-value>)',
               dark: 'rgb(var(--success-dark) / <alpha-value>)',
               fg: 'rgb(var(--success-fg) / <alpha-value>)',
            },
            warning: {
               light: 'rgb(var(--warning-light) / <alpha-value>)',
               DEFAULT: 'rgb(var(--warning) / <alpha-value>)',
               dark: 'rgb(var(--warning-dark) / <alpha-value>)',
               fg: 'rgb(var(--warning-fg) / <alpha-value>)',
            },
            info: {
               light: 'rgb(var(--info-light) / <alpha-value>)',
               DEFAULT: 'rgb(var(--info) / <alpha-value>)',
               dark: 'rgb(var(--info-dark) / <alpha-value>)',
               fg: 'rgb(var(--info-fg) / <alpha-value>)',
            },
            dark: {
               light: 'rgb(var(--success-light) / <alpha-value>)',
               DEFAULT: 'rgb(var(--success) / <alpha-value>)',
               dark: 'rgb(var(--success-dark) / <alpha-value>)',
               fg: 'rgb(var(--success-fg) / <alpha-value>)',
            },
         },
         boxShadow: {
            dropdown: 'var(--shadow-dropdown)',
            offcanvas: 'var(--shadow-offcanvas)',
            card: 'var(--shadow-card)',
            DEFAULT: 'var(--shadow-DEFAULT)',
            lg: 'var(--shadow-lg)',
            xl: 'var(--shadow-xl)',
            '2xl': '0 7px 40px -3px rgba(0, 0, 0, 0.18) ',
         },
         spacing: {
            px: em(1),
            0.5: em(2),
            1: em(4),
            1.5: em(6),
            2: em(8),
            2.5: em(10),
            3: em(12),
            3.5: em(14),
            4: em(16),
            4.5: em(18),
            5: em(20),
            5.5: em(22),
            6: em(24),
            6.5: em(26),
            7: em(28),
            7.5: em(30),
            8: em(32),
            8.5: em(34),
            9: em(36),
            9.5: em(38),
            10: em(40),
            10.5: em(42),
            screen: 'var(--screen)',
            DEFAULT: 'var(--size-D)',
            xs: 'var(--size-xs)',
            sm: 'var(--size-sm)',
            md: 'var(--size-md)',
            lg: 'var(--size-lg)',
            xl: 'var(--size-xl)',
            '2xl': 'var(--size-2xl)',
            42: em(172),
         },
         maxHeight: {
            screen: 'var(--screen)',
         },
         height: {
            screen: 'var(--screen)',
         },
         minHeight: {
            DEFAULT: 'var(--size-D)',
            screen: 'var(--screen)',
            xs: 'var(--size-xs)',
            sm: 'var(--size-sm)',
            md: 'var(--size-md)',
            lg: 'var(--size-lg)',
            xl: 'var(--size-xl)',
            '2xl': 'var(--size-2xl)',
         },
         minWidth: {
            DEFAULT: 'var(--size-D)',
            xs: 'var(--size-xs)',
            sm: 'var(--size-sm)',
            md: 'var(--size-md)',
            lg: 'var(--size-lg)',
            xl: 'var(--size-xl)',
            '2xl': 'var(--size-2xl)',
         },
         maxWidth: {
            container: '1200px',
            DEFAULT: 'var(--size-D)',
            xs: 'var(--size-xs)',
            sm: 'var(--size-sm)',
            md: 'var(--size-md)',
            lg: 'var(--size-lg)',
            xl: 'var(--size-xl)',
            '2xl': 'var(--size-2xl)',
         },
         screens: {
            xs: '490px',
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1200px',
            '2xl': '1400px',
            '3xl': '1490px',
         },
         margin: {
            7.5: '1.88rem',
         },
         borderRadius: {
            DEFAULT: 'var(--rounded-md)',
            md: 'var(--rounded-md)',
            lg: 'var(--rounded-lg)',
            sm: 'var(--rounded-sm)',
            xl: 'var(--rounded-lg)',
         },
         borderWidth: {
            3: '3px',
         },
         fontFamily: {
            body: ['Roboto', 'sans-serif'],
         },
      },
      fontSize: {
         '-fs-8': em(10),
         '-fs-7': em(10.5),
         '-fs-6': em(11),
         '-fs-5': em(11.5),
         '-fs-4': em(12.2),
         '-fs-3.5': em(13),
         '-fs-3': em(13.8),
         '-fs-2.5': em(14.1),
         '-fs-2': em(14.8),
         '-fs-1': em(15.6),
         DEFAULT: em(16),
         'fs-0.5': em(16.5),
         'fs-1': em(17),
         'fs-1.5': em(17.5),
         'fs-2': em(18.2),
         'fs-2.5': em(18.7),
         'fs-3': em(19.2),
         'fs-3.5': em(19.7),
         'fs-4': em(20.2),
         'fs-4.5': em(21.7),
         'fs-5': em(23),
         'fs-5.5': em(24.5),
         'fs-6': em(26),
         'fs-6.5': em(27),
         'fs-7': em(28),
         'fs-7.5': em(29),
         'fs-8': em(30),
         'fs-8.5': em(31),
         'fs-9': em(32),
         'fs-9.5': em(33),
         'fs-10': em(34),
         'fs-11': em(36),
         'fs-12': em(38),
         'fs-13': em(40),
         'fs-14': em(42),
         'fs-15': em(44),
         'fs-16': em(46),
         'fs-17': em(48),
         'fs-18': em(50),
         'fs-19': em(52),
         'fs-20': em(54),
         'fs-24': em(58),
         'fs-28': em(62),
         'fs-30': em(66),
         'fs-34': em(70),
         'fs-36': em(74),
         'fs-40': em(82),
         'fs-45': em(90),
         'fs-50': em(100),
      },
   },
   plugins: [],
}
